runtime: custom
env: flex

service: backend

containers:
  - name: backend
    image: gcr.io/steel-sonar-413417/backend:latest
    ports:
      - containerPort: 80
    env:
      - name: DATABASE_URL
        value: "pgsql://postgres:password@localhost:5432/monuments"

  - name: postgres
    image: gcr.io/steel-sonar-413417/postgres:latest
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_DB
        value: monuments
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: 20050404iliA

  - name: redis
    image: gcr.io/steel-sonar-413417/redis:latest
    ports:
      - containerPort: 6379

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

update_strategy:
  type: rolling
  max_surge: 30%
  max_unavailable: 30%

handlers:
  - url: /.*
    script: auto
    secure: always
