runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  APP_KEY: YOUR_APP_KEY
  APP_ENV: production
  APP_DEBUG: false
  APP_LOG_LEVEL: error
  DB_CONNECTION: pgsql
  DB_HOST: /cloudsql/YOUR_PROJECT_ID:REGION:INSTANCE_NAME
  DB_DATABASE: monuments
  DB_USERNAME: postgres
  DB_PASSWORD: 20050404iliA
  

beta_settings:
  cloud_sql_instances: YOUR_PROJECT_ID:REGION:INSTANCE_NAME