version: '3.5'

services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        image: backend
        environment:
            - DATABASE_URL=0.0.0.0
            - REDIS_HOST=redis
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        depends_on:
            - postgres


    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: monuments
            POSTGRES_USER: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: ["postgres", "-c", "log_statement=all"]


    redis:
        image: redis
        restart: always

volumes:
    postgres-data:
