version: '3.5'

services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        image: backend
        environment:
            - DATABASE_URL=185.112.102.43
        ports:
            - "8080:8080"
        volumes:
            - .:/app
