version: '3.5'

services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        image: backend
        ports:
            - "8080:8080"
        volumes:
            - .:/app
