services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: us-central1-docker.pkg.dev/steel-sonar-413417/backend:latest
        ports:
            - "80:80"
        depends_on:
            - redis
            - postgres
        environment:
            - DATABASE_URL=pgsql://postgres:20050404iliA@postgres/monuments
            - REDIS_HOST=redis
        volumes:
            - .:/app

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: monuments
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 20050404iliA
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis
        restart: always

volumes:
    postgres-data:
