version: '3.5'

services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        image: backend
        environment:
            DB_CONNECTION: mysql
            DB_HOST: 185.112.102.43
            DB_PORT: 3306
            DB_DATABASE: monuments
            DB_USERNAME: user
            DB_PASSWORD: root

        ports:
            - "8080:8080"
        volumes:
            - .:/app
