runtime: php
env: flex

service: default

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

network:
  forwarded_ports:
    - 80:80

env_variables:
  DB_CONNECTION: "pgsql"
  DB_HOST: "pgsql://postgres:20050404iliA@0.0.0.0/monuments"
  DB_DATABASE: "monuments"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "20050404iliA"
  REDIS_HOST: "redis"

runtime_config:
  document_root: public
