name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/steel-sonar-413417/monuments-backend:latest

      - name: Configure gcloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: steel-sonar-413417
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend --image=gcr.io/steel-sonar-413417/monuments-backend:latest --platform=managed --region=us-central-1 --allow-unauthenticated
