name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/steel-sonar-413417/monuments-backend:latest

      - name: Configure gcloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: steel-sonar-413417
          service_account_key: nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPqyFIoAouOHk0\nFnBemQB+zC5SVIsSzVKLefd0pVZWGi2KstucuCOSyzYPr2NVuTJ2v9DrXMRGI6V5\nYpYJODex5xu/LGNkb/B7mQrHZoN2ku1XvIeXOjn5Sw7Y8tNBhT/AIcbJEZNe7eKV\nAvaLqBZkpYfhlWofUCQWZUIGE+cTyZyfHzJSGXhGHR7QMGicfSZRU04uMO/7m9GT\nKsD1hFZ7L7MkYpSxKSDWmL0bNPqsx4iNyRVWzR7wjlrPUaWY4QO57g6TBlkUkrm5\nf4go/En3Z3NoFfxFVvhSzW9yzvSxc5x4egeNL+ESxzvLUco+8OFSD3dEphNsCCdK\nve2MM4NDAgMBAAECggEAALrsBS4QlocEBPAmsCMIJ0VoOpK8GLuKpuabT7PTZ75h\n0cDhz11lzzGbbulBrANYisqhlCJGFK4x+gkj/Q0q1htwWEApRnIhK1TwkOfGFSET\naEX+bJ/XEle/pXkPYfNzRhM85h6oIP5RalhtCTT0zg6lOYUcio2k3kRu4EgF60IH\nToCF9PHwfIf0IRVGnAUYPLlF4sP2xwJ9XVALne3Xi9W6vMusgbPvXjwxRwSzOLfI\nl3LUr/UCdSqCYXK7j4JYv+5u2tn8fU1n5iEIPxCsVGHpXvKbVcyMzVBB0q0CGJWI\n1claHjCD7P5+NIWmAw2NMIA670vZKbqLO+rNHYYIwQKBgQDwd0z+w6ljhV0S3u0f\nZksazMT2fln2diSTbiJ9LB9XqqnNgsXpo/xnhI/aD5pN2VadXoPtb1Wi9mR8UnJe\nd3GZk8+p8HIIjA2vIf6vIIZIKSkP7UY3N3qL1rFU92EWlWQl1kzP1+Aa9oimXLHf\n0TK72C2/6xHomD3tThNYwG014wKBgQDdFXDg0vUTwQ4IkZYoMFWgv6oTFMmsvBU4\nVU0QjTWl0c3Ks7lgWz7lkgHPcsp/ck352HZdJi05H6fppQ8KPAr7D2D4tpg4kJJO\n4L7N0K8uLsoCqfkyRbIshHSrxth1BSPyjBESwwz8xo09zqX9AxkiuEPKmpLdDZGb\nt23q7q77IQKBgB7CM+AWqREo2vnx+ATfMdYwwTUCfoFvJUiSeujl/vBYzTWTd7tm\nFYAsTbZH7qXsmg6xK1Dwv9SDjeD1Ltn0j1xksth7ACsltw5i29AM6gBK+4yk/ilL\n+GnwwWgr6IhZ/aB1ZAfmBi2MwXf+PWZyvPmYMmntKLJG3wz+wqzEmHOfAoGBAKPp\nOpglL7imoE3wCoDfXQziLSkad2+OvrjWXV2RJB49j7LiTuVGoTo5Zwgz1jhpObCs\nMQ1cuZiphKdwTddLruR2gXHEhtUhMqgybqRPPSIjZHhXJr+D9taUmZ+lvGP+HKm9\n+QaNADsExkD1zhDo1CDutqwmsA4d+j+V3nOY5LihAoGAasq8jg21Y3Gc/oMK3b1o\nS3alGdIQ0AGmaLTdkwR1fqrn7dkR89D8ZiK9wN7/Y5IGrBgxDmYyZYRhMzAVnFHR\neTGSDj+oij+svmJu0+2njTjHB+SdJgVUBwF9z4l3Y8UYpUEs/Cc9v9Mlj8HqfOiD\n7laqMdVdvPBVR1zQW1MbgyE=
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend --image=gcr.io/steel-sonar-413417/monuments-backend:latest --platform=managed --region=us-central-1 --allow-unauthenticated
