name: Deploy to Google Cloud Run via CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run multi-container app with docker-compose
        run: |
          docker-compose up --build -d

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Push
        run: |
          docker-compose push

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend --image=gcr.io/steel-sonar-413417/backend:latest --platform=managed --region=us-central1 --allow-unauthenticated --quiet --project=steel-sonar-413417
