name: Deploy to Google Cloud via CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.7.0
        id: auth
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: steel-sonar-413417
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set credentials path
        run: echo "::set-output name=GOOGLE_APPLICATION_CREDENTIALS_PATH::${{ steps.auth.outputs.credentials_file_path }}"
        id: set_creds_path

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build --no-cache
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Configure Docker for Google Cloud authentication
        run: |
          gcloud auth configure-docker
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Tag and push Docker images
        run: |
          docker pull postgres:latest
          docker tag postgres:latest gcr.io/steel-sonar-413417/postgres:latest
          docker push gcr.io/steel-sonar-413417/postgres:latest

          docker pull redis:latest
          docker tag redis:latest gcr.io/steel-sonar-413417/redis:latest
          docker push gcr.io/steel-sonar-413417/redis:latest

          docker tag gcr.io/steel-sonar-413417/backend:latest gcr.io/steel-sonar-413417/backend:latest
          docker push gcr.io/steel-sonar-413417/backend:latest
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
