name: Deploy to Google Cloud Run via Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/steel-sonar-413417/cloud-run-source-deploy/monuments-backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud auth configure-docker
          docker-compose up -d
          gcloud run deploy backend --image=us-central1-docker.pkg.dev/steel-sonar-413417/cloud-run-source-deploy/monuments-backend:latest --platform=managed --region=us-central1 --allow-unauthenticated
