name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i '185.112.102.43,' -u root playbook.yml --extra-vars "ansible_ssh_pass=9b665MbJMRpP"

      - name: Build
        run: |
          cd / && docker-compose -f /MonumentsBack/docker-compose.yml up -d
